# Generated by Django 2.0.6 on 2018-12-29 22:02

from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields
import inia.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('treatment', django_enumfield.db.fields.EnumField(default='CIA', enum=inia.models.TreatmentType)),
            ],
        ),
        migrations.CreateModel(
            name='GeneAliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Homologene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homologene_group_id', models.IntegerField()),
                ('gene_symbol', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('species', django_enumfield.db.fields.EnumField(default='HOMO_SAPIENS', enum=inia.models.SpeciesType)),
                ('brain', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='IniaGene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField()),
                ('uniqueID', models.CharField(max_length=255)),
                ('microarray', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('phenotype', models.CharField(max_length=255)),
                ('species', django_enumfield.db.fields.EnumField(default='HOMO_SAPIENS', enum=inia.models.SpeciesType)),
                ('brain_region', models.CharField(max_length=255)),
                ('paradigm', models.CharField(max_length=255)),
                ('paradigm_duration', models.CharField(max_length=255)),
                ('alcohol', models.BooleanField()),
                ('gene_symbol', models.CharField(max_length=255)),
                ('gene_name', models.CharField(max_length=255)),
                ('p_value', models.FloatField()),
                ('fdr', models.FloatField()),
                ('direction', django_enumfield.db.fields.EnumField(default='DOWN', enum=inia.models.regulationDirection)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inia.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField()),
                ('authors', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('journal', models.CharField(max_length=255)),
                ('pages', models.CharField(max_length=15)),
                ('date_sub', models.DateTimeField()),
                ('doi', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('display', models.CharField(max_length=255)),
                ('htmlid', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='iniagene',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inia.Publication'),
        ),
        migrations.AddField(
            model_name='genealiases',
            name='IniaGene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inia.IniaGene'),
        ),
    ]
