# Generated by Django 2.0.6 on 2019-01-02 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iniagene',
            name='publication',
        ),
    ]
