# Generated by Django 2.0.6 on 2018-12-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniagene',
            name='homologenes',
            field=models.ManyToManyField(to='inia.Homologene'),
        ),
    ]
