# Generated by Django 2.0.6 on 2018-12-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0002_iniagene_homologenes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homologene',
            name='homologene_group_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='iniagene',
            name='legacy_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='iniagene',
            name='p_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
