# Generated by Django 2.0.6 on 2018-12-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0003_auto_20181230_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniagene',
            name='gene_symbol',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
