# Generated by Django 2.1.5 on 2019-01-29 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0003_auto_20190104_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iniagene',
            old_name='uniqueID',
            new_name='probe_id',
        ),
    ]
