# Generated by Django 2.1.5 on 2019-02-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0006_auto_20190201_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='brain_region',
            field=models.ManyToManyField(blank=True, to='inia.BrainRegion'),
        ),
    ]
