# Generated by Django 2.1.5 on 2019-02-01 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0007_auto_20190201_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='brain_region',
            new_name='brain_regions',
        ),
    ]
