# Generated by Django 2.1.5 on 2019-02-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0008_auto_20190201_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='homologene',
            name='ncbi_uid',
            field=models.IntegerField(db_index=True, default=-1),
            preserve_default=False,
        ),
    ]
