# Generated by Django 2.1.7 on 2019-03-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0010_auto_20190207_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='species',
            field=models.CharField(choices=[('HOMO_SAPIENS', 'HOMO_SAPIENS'), ('MUS_MUSCULUS', 'MUS_MUSCULUS'), ('RATTUS_NORVEGICUS', 'RATTUS_NORVEGICUS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='homologene',
            name='species',
            field=models.CharField(choices=[('HOMO_SAPIENS', 'HOMO_SAPIENS'), ('MUS_MUSCULUS', 'MUS_MUSCULUS'), ('RATTUS_NORVEGICUS', 'RATTUS_NORVEGICUS')], max_length=255),
        ),
    ]
