# Generated by Django 2.2 on 2019-06-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0013_auto_20190622_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homologene',
            name='gene_symbol',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
