# Generated by Django 2.2 on 2019-06-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inia', '0014_auto_20190622_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniagene',
            name='gene_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
